spring.application.name=gameShop
app.upload.dir=uploads/images

# Base de datos MySQL (ajusta usuario y contraseña si es necesario)
db.url=jdbc:mysql://localhost:3306/gameshop_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
db.user=root
db.password=root

# Configuraci�n de subida de archivos (m�x. 10 MB)
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
